version: '3.7'

services:
  backend:
    ports:
      - 5020:8080
    environment:
      - ICON_HOST="https://${LBNL_HOST}:${LBNL_HTTP_PORT}"
      # https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-3.1#starting-a-container-with-https-support-using-docker-compose
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${LBNL_SSL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/ssl/${LBNL_SSL_CERTIFICATE_BASE_FILE_NAME}.pfx

  nginx:
    ports:
      - ${LBNL_HTTP_PORT}:80
      - ${LBNL_HTTPS_PORT}:443
    environment:
      - SERVER_NAME=${LBNL_HOST}
      - SSL_CERTIFICATE_BASE_FILE_NAME=${LBNL_SSL_CERTIFICATE_BASE_FILE_NAME}
