version: '3.7'

services:
  backend:
    ports:
      - 5000:8080
    environment:
      - ICON_HOST="https://${HOST}:${HTTP_PORT}"

  nginx:
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    environment:
      - SERVER_NAME=${HOST}
