version: '3.3'

services:
  reverse_proxy: # https://hub.docker.com/_/nginx
    restart: always
    image: nginx:1.19.9-alpine
    command: [
      "nginx",
      "-g", "daemon off;"
      ]
    ports:
      - 7000:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
